### ISSUE TITLE
Deprecation warning (Windows)

### ISSUE THREAD

**Issue by brandstaetter** [keepcosmos/terjira#113]
I get this deprecation warning when running jira commands on Windows (seems to work on MacOS):

```Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
x```

running ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x64-mingw-ucrt] 

MacOS is running on ruby 2.6.10p210

**Comment by funktionalsystems** [comment]
Just hit this on Mac as well, and it's now an error.

Arrange:
```
brew install rbenv
rbenv install 3.4.1
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.zshrc 
echo 'eval "$(rbenv init -)"' >> ~/.zshrc 
source  ~/.zshrc
gem install terjira --user-install
echo 'export PATH="$HOME/.gem/ruby/3.4.0/bin:$PATH"' >> ~/.zshrc
source  ~/.zshrc
```

Act: `jira`

Assert:
```
~/.gem/ruby/3.4.0/gems/thor-1.0.1/lib/thor/error.rb:105:in '<class:Thor>': uninitialized constant DidYouMean::SPELL_CHECKERS (NameError)

    DidYouMean::SPELL_CHECKERS.merge!(
              ^^^^^^^^^^^^^^^^
Did you mean?  DidYouMean::SpellChecker
        from ~/.gem/ruby/3.4.0/gems/thor-1.0.1/lib/thor/error.rb:1:in '<top (required)>'
        from ~/.gem/ruby/3.4.0/gems/thor-1.0.1/lib/thor/base.rb:3:in 'Kernel#require_relative'
        from ~/.gem/ruby/3.4.0/gems/thor-1.0.1/lib/thor/base.rb:3:in '<top (required)>'
        from ~/.gem/ruby/3.4.0/gems/thor-1.0.1/lib/thor.rb:2:in 'Kernel#require_relative'
        from ~/.gem/ruby/3.4.0/gems/thor-1.0.1/lib/thor.rb:2:in '<top (required)>'
        from <internal:~/.rbenv/versions/3.4.1/lib/ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require'
        from <internal:~/.rbenv/versions/3.4.1/lib/ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require'
        from ~/.gem/ruby/3.4.0/gems/terjira-0.4.8/lib/terjira.rb:3:in '<top (required)>'
        from <internal:~/.rbenv/versions/3.4.1/lib/ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require'
        from <internal:~/.rbenv/versions/3.4.1/lib/ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require'
        from ~/.gem/ruby/3.4.0/gems/terjira-0.4.8/bin/jira:5:in '<top (required)>'
        from ~/.gem/ruby/3.4.0/bin/jira:25:in 'Kernel#load'
        from ~/.gem/ruby/3.4.0/bin/jira:25:in '<main>'
```
