### ISSUE TITLE
jira <issue|sprint> ls report '301 Moved Permanently' error

### ISSUE THREAD

**Issue by albasili** [keepcosmos/terjira#30]
Hi there,

for some reasons when I send the command
```bash
jira sprint ls
```
or 
```bash
jira issue ls
```
I receive the following message:
```bash
/usr/lib/ruby/2.3.0/json/common.rb:156:in `parse': 784: unexpected token at '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> (JSON::ParserError)
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://jira.melexis.com/jirarest/agile/1.0/board?">here</a>.</p>
<hr>
<address>Apache/2.2.16 (Debian) Server at jira.melexis.com Port 443</address>
</body></html>
'
        from /usr/lib/ruby/2.3.0/json/common.rb:156:in `parse'
        from /var/lib/gems/2.3.0/gems/terjira-0.3.3/bin/jira:14:in `rescue in <top (required)>'
        from /var/lib/gems/2.3.0/gems/terjira-0.3.3/bin/jira:9:in `<top (required)>'
        from /usr/local/bin/jira:22:in `load'
        from /usr/local/bin/jira:22:in `<main>'
```
Any idea why? Anything related to my Jira server configuration?

**Comment by keepcosmos** [comment]
I think it is related to your terjira configuration about your jira system.

**Comment by albasili** [comment]
Could you be more specific? I've seen the .terjira folder with the related files, but I haven't been able to spot the issue.

**Comment by keepcosmos** [comment]
Could you check your jira rest api endpoint? I think the URL that you entered is not suitable.

**Comment by albasili** [comment]
Uhm, I'm sorry but I have no idea how to get that URL, should I ask my IT?

**Comment by albasili** [comment]
After several trials I found out the context path needed to start with a forward slash!
Sorry for bothering,

Al

**Comment by keepcosmos** [comment]
Good! 👍
