### ISSUE TITLE
Parse issue detail error

### ISSUE THREAD

**Issue by zhea55** [keepcosmos/terjira#42]
```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `parse': 757: unexpected token at '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><title>Oops, you&#39;ve found a dead link. - JIRA</title><script type="text/javascript">contextPath = "";</script><link type='text/css' rel='stylesheet' href='/static-assets/metal-all.css' media='all'><script src='/static-assets/metal-all.js'></script><!--[if lt IE 9]><link type='text/css' rel='stylesheet' href='/static-assets/metal-all-ie.css' media='all'><script src='/static-assets/metal-all-ie.js'></script><![endif]--><!--[if IE 9]><link type='text/css' rel='stylesheet' href='/static-assets/metal-all-ie9.css' media='all'><![endif]--><meta name="decorator" content="none" /></head><body class=" error-page error404"><script type="text/javascript">document.body.className += " js-enabled";</script><div id="page"><header id="header" role="banner"></header><!-- #header --><section id="content" role="main"><div class="aui-page-panel"><div class="aui-page-panel-inner"><section class="aui-page-panel-content lowerContent"><div id="error-state"><span class="error-type"></span><h1>Oops, you&#39;ve found a dead link.</h1><ul><li>Go back to the <a href="javascript:window.history.back()">previous page</a></li><li>Go to the <a href="/secure/MyJiraHome.jspa">Home Page</a></li></ul></div></section><!-- .aui-page-panel-content --></div><!-- .aui-page-panel-inner --></div><!-- .aui-page-panel --></section><!-- #content --><footer id="footer" role="contentinfo"><section class="footer-body"> (JSON::ParserError)


<ul class="atlassian-footer">
    <li>
        Atlassian JIRA <a class="seo-link" href="https://www.atlassian.com/software/jira">Project Management Software</a>



        <span id="footer-build-information">(v6.3.6#6336-<span title='cf1622c62a612607f341bda9491a04918e09ebfd' data-commit-id='cf1622c62a612607f341bda9491a04918e09ebfd}'>sha1:cf1622c</span>)</span>
    </li>
    <li>
        <a id="about-link" href="/secure/AboutPage.jspa">About JIRA</a>
    </li>
    <li>
                        <a id="footer-report-problem-link" href="/secure/CreateIssue!default.jspa">Report a problem</a>
    </li>
</ul>
<div id="footer-logo"><a href="http://www.atlassian.com/">Atlassian</a></div></section></footer><!-- #footer --></div><!-- #page --></body></html>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `parse'
	from /Library/Ruby/Gems/2.0.0/gems/terjira-0.3.6/bin/jira:14:in `rescue in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/terjira-0.3.6/bin/jira:9:in `<top (required)>'
	from /usr/local/bin/jira:23:in `load'
	from /usr/local/bin/jira:23:in `<main>'

```

**Comment by keepcosmos** [comment]
Check your jira api endpoint

**Comment by zhea55** [comment]
My endpoint is ok.
I can list my issues.

but can not see the detail when I typed the right issue key.

**Comment by keepcosmos** [comment]
Is it happen all of issues?

**Comment by zhea55** [comment]
yes

All issue [issue_key] command fail.

print jira(http 404 code)

Is there a debug mode, so i can see the request url?

**Comment by keepcosmos** [comment]
Ok, you can pull code and run `bin/terjira {command}`. If you need hep, just let me know.

**Comment by zhea55** [comment]
```html
/Library/Ruby/Gems/2.0.0/gems/json-2.1.0/lib/json/common.rb:156:in `parse': 765: unexpected token at '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><title>Oops, you&#39;ve found a dead link. - JIRA</title><script type="text/javascript">contextPath = "";</script><link type='text/css' rel='stylesheet' href='/static-assets/metal-all.css' media='all'><script src='/static-assets/metal-all.js'></script><!--[if lt IE 9]><link type='text/css' rel='stylesheet' href='/static-assets/metal-all-ie.css' media='all'><script src='/static-assets/metal-all-ie.js'></script><![endif]--><!--[if IE 9]><link type='text/css' rel='stylesheet' href='/static-assets/metal-all-ie9.css' media='all'><![endif]--><meta name="decorator" content="none" /></head><body class=" error-page error404"><script type="text/javascript">document.body.className += " js-enabled";</script><div id="page"><header id="header" role="banner"></header><!-- #header --><section id="content" role="main"><div class="aui-page-panel"><div class="aui-page-panel-inner"><section class="aui-page-panel-content lowerContent"><div id="error-state"><span class="error-type"></span><h1>Oops, you&#39;ve found a dead link.</h1><ul><li>Go back to the <a href="javascript:window.history.back()">previous page</a></li><li>Go to the <a href="/secure/MyJiraHome.jspa">Home Page</a></li></ul></div></section><!-- .aui-page-panel-content --></div><!-- .aui-page-panel-inner --></div><!-- .aui-page-panel --></section><!-- #content --><footer id="footer" role="contentinfo"><section class="footer-body"> (JSON::ParserError)


<ul class="atlassian-footer">
    <li>
        Atlassian JIRA <a class="seo-link" href="https://www.atlassian.com/software/jira">Project Management Software</a>



        <span id="footer-build-information">(v6.3.6#6336-<span title='cf1622c62a612607f341bda9491a04918e09ebfd' data-commit-id='cf1622c62a612607f341bda9491a04918e09ebfd}'>sha1:cf1622c</span>)</span>
    </li>
    <li>
        <a id="about-link" href="/secure/AboutPage.jspa">About JIRA</a>
    </li>
    <li>
                        <a id="footer-report-problem-link" href="/secure/CreateIssue!default.jspa">Report a problem</a>
    </li>
</ul>
<div id="footer-logo"><a href="http://www.atlassian.com/">Atlassian</a></div></section></footer><!-- #footer --></div><!-- #page --></body></html>'
	from /Library/Ruby/Gems/2.0.0/gems/json-2.1.0/lib/json/common.rb:156:in `parse'
	from bin/terjira:14:in `rescue in <main>'
	from bin/terjira:9:in `<main>'
```

Same 404 error, no request url print.
