### ISSUE TITLE
Basic authentication with passwords is deprecated

### ISSUE THREAD

**Issue by vokracko** [keepcosmos/terjira#97]
https://confluence.atlassian.com/cloud/deprecation-of-basic-authentication-with-passwords-for-jira-and-confluence-apis-972355348.html
```
Login will be required...
Site (ex: https://myjira.atlassian.net): x
Jira path in your site (just press enter if you don't have): x 
Username: x
Password: x
Traceback (most recent call last):
	17: from /usr/bin/jira:23:in `<main>'
	16: from /usr/bin/jira:23:in `load'
	15: from /home/gwi/.gem/ruby/2.7.0/gems/terjira-0.4.6/bin/jira:10:in `<top (required)>'
	14: from /usr/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	13: from /usr/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	12: from /usr/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	11: from /usr/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	10: from /usr/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
	 9: from /usr/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
	 8: from /usr/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	 7: from /usr/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	 6: from /usr/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	 5: from /home/gwi/.gem/ruby/2.7.0/gems/terjira-0.4.6/lib/terjira/board_cli.rb:14:in `list'
	 4: from /home/gwi/.gem/ruby/2.7.0/gems/terjira-0.4.6/lib/terjira/client/board.rb:10:in `all'
	 3: from /home/gwi/.gem/ruby/2.7.0/gems/terjira-0.4.6/lib/terjira/client/base.rb:55:in `block (3 levels) in singleton class'
	 2: from /usr/lib/ruby/gems/2.7.0/gems/jira-ruby-1.7.1/lib/jira/client.rb:220:in `get'
	 1: from /usr/lib/ruby/gems/2.7.0/gems/jira-ruby-1.7.1/lib/jira/client.rb:242:in `request'
/usr/lib/ruby/gems/2.7.0/gems/jira-ruby-1.7.1/lib/jira/request_client.rb:15:in `request': Unauthorized (JIRA::HTTPError)
	5: from /usr/bin/jira:23:in `<main>'
	4: from /usr/bin/jira:23:in `load'
	3: from /home/gwi/.gem/ruby/2.7.0/gems/terjira-0.4.6/bin/jira:9:in `<top (required)>'
	2: from /home/gwi/.gem/ruby/2.7.0/gems/terjira-0.4.6/bin/jira:14:in `rescue in <top (required)>'
	1: from /usr/lib/ruby/gems/2.7.0/gems/json-2.3.1/lib/json/common.rb:263:in `parse'
/usr/lib/ruby/gems/2.7.0/gems/json-2.3.1/lib/json/common.rb:263:in `parse': 784: unexpected token at 'Basic authentication with passwords is deprecated.  For more information, see: https://confluence.atlassian.com/cloud/deprecation-of-basic-authentication-with-passwords-for-jira-and-confluence-apis-972355348.html (JSON::ParserError)
'
```

**Comment by ghosteathuman** [comment]
Thanks @vokracko for raising this issue.

There was just a discussion about this [here](https://github.com/keepcosmos/terjira/issues/71#issuecomment-691427463).

Would it have been a better experience if instead of `Password`, `API Token` was used instead during the prompt?

**Comment by ghosteathuman** [comment]
@vokracko Just FYI, using API Tokens on the `Password` field would still work.

I am making changes to ensure it is made explicitly clear what ought to be filled in that field.

**Comment by vokracko** [comment]
I overlooked it in the README :facepalm: 
Stating it explicitly in the prompt is better :+1: 

Thanks for the quick reaction
